Formatting の追加
monaqa/satysfi-language-server pull request #2
Opened 2023-01-27 13:02 UTC by usagrada

formattingを可能にしました。
フォーマッタの方でもLSP の互換性を持つよう変更を行いました。手元の環境で、フォーマットのリクエストが動作することを確認（VS）しております。

v0.1.x に切り替わるタイミングで、修正が必要になるとは思いますが、v0.0.x に関しては、現在の設計でいかがでしょうか？
修正等があれば、こちらで直す形でも直していただく形でも大丈夫です（そのままCloseしていただいても構いません）。

今後、別のフォーマッタに切り替えたい場合には `async fn formatting(&self, params: DocumentFormattingParams) -> Option<Vec<TextEdit>>` の内部を書き換えることで、切り替えることができます。

2023-01-27 14:57 UTC, monaqa requested changes
ありがとうございます。
今回は新たに `document_formatting_provider` の機能を有効化するため、server capabilities の該当部分のフラグも立てていただければと思います。

https://github.com/monaqa/satysfi-language-server/blob/c48b59c248b5e4deb6dc9cd6a2a0df27af53bbce/src/language_server/capabilities.rs#L35

2023-01-28 07:51 UTC, usagrada commented
ありがとうございます。document_formatting_provider のフラグをオンにさせていただきました。確認の方、よろしくお願いできますでしょうか？

2023-01-29 06:14 UTC, monaqa approved these changes
ありがとうございます。
SATySFi v0.1.0 が正式リリースされた暁には、satysfi-language-server の構成にも大きく見直しが入ると思われますので、予めご了承ください。

本 PR のステータスは Draft となっていますが、まだマージされると困る事情などありますでしょうか？
特になければ README だけ編集してマージしようと思っています。

2023-01-29 06:25 UTC, usagrada commented
確認ありがとうございます。
> SATySFi v0.1.0 が正式リリースされた暁には、satysfi-language-server の構成にも大きく見直しが入ると思われますので、予めご了承ください。

承知いたしました。同じく、SATySFi v0.1.0 が正式リリースされた場合、現状のフォーマッタでは動作しなくなるため、その時にはフォーマッタを削除していただいて構いません。お手数おかけしますがお願いいたします。

大きな修正があった場合のためにDraftでPRを送らせていただいていました。特に困る事情等についてはありませんので、Draftを解除させていただきます。よろしくお願いいたします。

2023-02-01 09:45 UTC, monaqa commented
ありがとうございます。こちらマージして README を書き換えます。

2023-02-01 09:45 UTC, merged